import React from "react";
import Link from "next/link";
const Home = () => {
  return (
    <div
      style={{
        height: "100vh",
        padding: "20px",
        backgroundColor: "#232323",
        color: "white",
      }}
    >
      {" "}
      <h1 style={{ fontSize: "48px", marginBottom: "20px" }}>Homepage</h1>{" "}
      <p style={{ fontSize: "18px", marginBottom: "30px" }}>
        {" "}
        This project was generated By{" "}
        <a
          href="https://www.dhiwise.com"
          style={{ color: "#87CEFA", textDecoration: "none" }}
        >
          {" "}
          Dhiwise{" "}
        </a>{" "}
        . Quickly use below links to navigate through all pages.{" "}
      </p>{" "}
      <ul style={{ listStyle: "none", padding: "0" }}>
        {" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            href="/home1"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            Home1{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            href="/createpost"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            CreatePost{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            href="/conectwallet"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            Conectwallet{" "}
          </Link>
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            href="/postpopular"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            PostPopular{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            href="/postpreview"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            Postpreview{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            href="/clipspreview"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            Clipspreview{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            href="/trendingsearchtop"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            TrendingsearchTop{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            href="/trendingsearchlatest"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            TrendingsearchLatest{" "}
          </Link>{" "}
        </li>
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            href="/trendingsearchpeople"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            TrendingsearchPeople{" "}
          </Link>{" "}
        </li>{" "}
        <li style={{ marginBottom: "10px" }}>
          {" "}
          <Link
            href="/trendingsearchmedia"
            style={{ color: "#87CEFA", textDecoration: "none" }}
          >
            {" "}
            Trendingsearchmedia{" "}
          </Link>{" "}
        </li>{" "}
      </ul>{" "}
    </div>
  );
};
export default Home;
